# Generated by Django 3.2.8 on 2021-10-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, verbose_name='Имя')),
                ('tel', models.CharField(max_length=13, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='gg', max_length=20, verbose_name='Логин')),
                ('name', models.CharField(default='', max_length=10, verbose_name='Имя')),
                ('tel', models.IntegerField(verbose_name='Телефон')),
                ('type_work', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateField(verbose_name='Дата записи')),
                ('time', models.TimeField(verbose_name='Время записи')),
            ],
        ),
    ]
